# Generated by Django 5.1.2 on 2024-11-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stickerId', models.CharField(max_length=50)),
                ('userId', models.IntegerField()),
                ('purchaseDate', models.DateField()),
                ('expiryDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('vehicleId', models.CharField(max_length=50)),
                ('vehicleManufacturer', models.CharField(max_length=100)),
                ('vehicleColor', models.CharField(max_length=50)),
                ('vehicleType', models.CharField(max_length=50)),
            ],
        ),
    ]
