# Generated by Django 5.1.2 on 2024-11-04 14:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('vehicle_manufacturer', models.CharField(max_length=100)),
                ('vehicle_color', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=20)),
                ('sticker', models.ForeignKey(db_column='sticker_id', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='parking.sticker')),
            ],
        ),
    ]
