# Generated by Django 5.1.2 on 2024-11-04 15:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_color',
            new_name='vehicleColor',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_manufacturer',
            new_name='vehicleManufacturer',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_type',
            new_name='vehicleType',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='plate_number',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='sticker',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='user_id',
        ),
        migrations.AddField(
            model_name='sticker',
            name='expiryDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='sticker',
            name='purchaseDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='sticker',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.vehicle'),
        ),
    ]
