# Generated by Django 5.1.2 on 2024-11-03 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='stickerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.sticker'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='stickerId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
