# Generated by Django 5.1.2 on 2024-11-03 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_remove_sticker_id_remove_vehicle_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sticker',
            old_name='expiryDate',
            new_name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='purchaseDate',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='stickerId',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='stickerId',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicleColor',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicleId',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicleManufacturer',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicleType',
        ),
        migrations.AddField(
            model_name='sticker',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sticker',
            name='vehicle',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='parking.vehicle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
