# Generated by Django 5.1.1 on 2024-11-03 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingArea',
            fields=[
                ('parking_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('parking_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('parking_lot_id', models.AutoField(primary_key=True, serialize=False)),
                ('parking_lot_number', models.CharField(max_length=10)),
                ('parking_lot_status', models.CharField(max_length=20)),
                ('parking_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_lots', to='myapp.parkingarea')),
            ],
        ),
    ]
