# Generated by Django 5.1.3 on 2024-11-22 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='plateNumber',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sticker',
            name='expiryDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='purchaseDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicle'),
        ),
    ]
