# Generated by Django 5.1.1 on 2024-11-28 10:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingArea',
            fields=[
                ('parking_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('parking_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('parking_lot_id', models.AutoField(primary_key=True, serialize=False)),
                ('parking_lot_number', models.CharField(max_length=10)),
                ('parking_lot_status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied')], default='Available', max_length=20)),
                ('parking_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_lots', to='myapp.parkingarea')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('entry_time', models.TimeField()),
                ('exit_date', models.DateField()),
                ('exit_time', models.TimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parking_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parkingarea')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parkinglot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
